package intro2.ui;

public final class HeaderSubPage implements lahaina.runtime.Page {

	public void HeaderSubPage() {}

	public void process(lahaina.runtime.Writer out, lahaina.runtime.State state) throws Exception {
		lahaina.tag.Tag tag = null;

		out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\"\"http://www.w3.org/TR/REC-html40/loose.dtd\">\r\n");
		out.write("<HTML>\r\n");
		out.write("<HEAD>\r\n");
		out.write("<!-- Generated by intro2 on ");
		intro2.ui.taglib.Date _tag0 = new intro2.ui.taglib.Date(state);
		tag = _tag0;
		while(_tag0.process(out));
		out.write("-->\r\n");
		out.write("<TITLE>\r\n");
		out.write(state.getStringAttribute("title"));
		out.write("</TITLE>\r\n");
		out.write("<LINK REL =\"stylesheet\" TYPE=\"text/css\" HREF=\"");
		intro2.ui.taglib.Dots _tag1 = new intro2.ui.taglib.Dots(state);
		tag = _tag1;
		while(_tag1.process(out));
		out.write("stylesheet.css\" TITLE=\"Style\">\r\n");
		out.write("</HEAD>\r\n");
		out.write("<BODY>\r\n");
		out.write("\r\n");
		intro2.ui.taglib.NavbarInit _tag2 = new intro2.ui.taglib.NavbarInit(state);
		tag = _tag2;
		while(_tag2.process(out));
	}
}
